version: '3.8'

services:
  photos-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photos-app
    ports:
      - "8080:8080"
    volumes:
      - photos_photos:/app/photos
      - photos_cache:/app/cache
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Enhanced memory and GC settings
      - JAVA_OPTS=-Xmx384m -Xms128m -XX:MaxRAMPercentage=75.0 -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      # Spring thread pool settings
      - SPRING_TASK_EXECUTION_POOL_CORE-SIZE=4
      - SPRING_TASK_EXECUTION_POOL_MAX-SIZE=8
      - SPRING_TASK_EXECUTION_POOL_QUEUE-CAPACITY=100
      - SPRING_TASK_SCHEDULING_POOL_SIZE=2
      # Tomcat thread optimizations
      - SERVER_TOMCAT_THREADS_MAX=50
      - SERVER_TOMCAT_THREADS_MIN-SPARE=5
      - SERVER_TOMCAT_MAX-CONNECTIONS=100
      # Database connection pool optimization
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=5
      # Photos application configuration
      - PHOTOS_DIRECTORY=/app/photos
      - PHOTOS_THUMBNAIL_WIDTH=400
      - PHOTOS_THUMBNAIL_HEIGHT=400
      # Website metadata configuration
      - PHOTOS_WEBSITE_TITLE=Photos
      - PHOTOS_WEBSITE_DESCRIPTION=Photography Portfolio
      - PHOTOS_WEBSITE_FAVICON_PATH=/favicon.ico
      - PHOTOS_WEBSITE_OG_IMAGE=
      - PHOTOS_WEBSITE_OG_URL=
      - PHOTOS_WEBSITE_OG_SITE_NAME=Photo Gallery
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  photos_photos:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/http/beanthemoonman.io/photos
  photos_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/http/beanthemoonman.io/cache